---
- name: Create Azure VM Instance
  azure_rm_virtualmachine:
    resource_group: "{{resource_group}}"
    name: "{{instance_name}}"
    vm_size: "{{vm_size}}"
    admin_username: azureuser
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/azureuser/.ssh/authorized_keys
        key_data: "{{ssh_keys}}"
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: '16.04-LTS'
      version: latest
    location: "{{location}}"
    virtual_network_name: "{{virtual_network_name}}"