---
- name: Create EC2 Instance
  amazon.aws.ec2_instance:
    name: "{{ instance_name }}"
    key_name: "{{ key_name }}"
    image_id: "{{ image }}"
    instance_type: "{{ instance_type }}"
    region: "{{ region }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    security_group: "{{ sec_group }}"
    count: 1
